#pragma once

#include <nlohmann/json.hpp>
#include <nlohmann/json_fwd.hpp>

static nlohmann::ordered_json CNLangData = {
    { "name", "简体中文" },
    { "commands.generic.target", "没有与选择器匹配的目标" },
    { "commands.generic.ui", "已将 UI 打开给玩家 {0}" },
    { "commands.generic.permission", "您没有权限执行此命令" },
    { "commands.language.description", "§e§lLOICollection -> §a语言设置" },
    { "commands.blacklist.description", "§e§lLOICollection -> §b服务器黑名单" },
    { "commands.blacklist.error.add", "玩家 {0} 无法被添加至黑名单" },
    { "commands.blacklist.error.remove", "对象 {0} 不在黑名单中" },
    { "commands.blacklist.error.info", "无法获取对象 {0} 的信息" },
    { "commands.blacklist.success.add", "已添加玩家 {0} 至黑名单" },
    { "commands.blacklist.success.remove", "已将对象 {0} 从黑名单中移除" },
    { "commands.blacklist.success.info", "目标对象查询的信息如下:" },
    { "commands.blacklist.success.list", "当前黑名单列表如下: {0}" },
    { "commands.mute.description", "§e§lLOICollection -> §b服务器禁言" },
    { "commands.mute.error.add", "玩家 {0} 无法被禁言" },
    { "commands.mute.error.remove", "玩家 {0} 没有被禁言" },
    { "commands.mute.error.info", "无法获取玩家 {0} 的信息" },
    { "commands.mute.success.add", "已将玩家 {0} 禁言" },
    { "commands.mute.success.remove", "已解除玩家 {0} 的禁言" },
    { "commands.mute.success.info", "玩家 {0} 的信息如下:" },
    { "commands.mute.success.list", "当前禁言列表如下: {0}" },
    { "commands.cdk.description", "§e§lLOICollection -> §b总换码" },
    { "commands.cdk.success.convert", "玩家 {0} 您的总换码 {1} 已进行兑换" },
    { "commands.menu.description", "§e§lLOICollection -> §b服务器菜单" },
    { "commands.menu.error.item.null", "当前物品无法初始化" },
    { "commands.menu.error.item.give", "无法给予玩家 {0} 物品" },
    { "commands.tpa.description", "§e§lLOICollection -> §b玩家互传" },
    { "commands.tpa.success.invite", "已向玩家 {0} 发送传送请求" },
    { "commands.tpa.error.invite", "无法发送传送请求, 目前所需 {0}" },
    { "commands.shop.description", "§e§lLOICollection -> §b服务器商店" },
    { "commands.pvp.description", "§e§lLOICollection -> §b服务器PVP" },
    { "commands.pvp.success.enable", "已开启 PVP 模式" },
    { "commands.pvp.success.disable", "已关闭 PVP 模式" },
    { "commands.wallet.description", "§e§lLOICollection -> §b个人钱包" },
    { "commands.wallet.error.score", "您没有足够的 Score" },
    { "commands.wallet.success.transfer", "您已将 {0} Score 转给 {1} 名玩家" },
    { "commands.chat.description", "§e§lLOICollection -> §b个人称号" },
    { "commands.chat.success.add", "添加称号 {0} 至玩家 {1}" },
    { "commands.chat.success.remove", "移除玩家 {0} 的称号 {1}" },
    { "commands.chat.success.set", "设置玩家 {0} 的称号为 {1}" },
    { "commands.chat.success.list", "玩家 {0} 的称号列表如下: {1}" },
    { "commands.notice.description", "§e§lLOICollection -> §a公告系统" },
    { "commands.market.description", "§e§lLOICollection -> §b玩家市场" },
    { "commands.behaviorevent.description", "§e§lLOICollection -> §b行为事件" },
    { "commands.behaviorevent.error.query", "没有查询到任何行为事件" },
    { "commands.behaviorevent.error.back", "没有指定行为事件" },
    { "commands.behaviorevent.success.clean", "已清除所有规定的行为事件" },
    { "commands.behaviorevent.success.query", "当前查询行为事件列表如下: {0}" },
    { "commands.behaviorevent.success.query.info", "目标行为事件信息:" },
    { "commands.behaviorevent.success.back", "区域行为事件已回溯" },
    { "generic.tips.noinput", "没有输入内容, 无法执行后续操作" },
    { "language.log", "玩家 {player}({player.uuid}) 将语言更改为 {player.language}" },
    { "language.gui.title", "§e§lLOICollection -> §a语言设置" },
    { "language.gui.label", "§a个人语言设置" },
    { "language.gui.lang", "§b当前语言: §r${language}" },
    { "language.gui.dropdown", "§e语言选择" },
    { "blacklist.log1", "已将玩家 {player}({player.uuid}) 添加进黑名单" },
    { "blacklist.log2", "已将 ${target} 从黑名单中移除" },
    { "blacklist.tips", "§4您已被服务器加入黑名单\n§a请联系管理员解决问题\n§e解除时间: §r${time}\n§b原因: §r${cause}" },
    { "blacklist.gui.title", "§e§lLOICollection -> §b服务器黑名单" },
    { "blacklist.gui.label", "§a功能如下:" },
    { "blacklist.gui.addBlacklist", "§c添加黑名单\n§4将玩家添加至黑名单" },
    { "blacklist.gui.removeBlacklist", "§a删除黑名单\n§4将玩家从黑名单中移除" },
    { "blacklist.gui.add.title", "§eLOIBlacklist §b-> §c添加黑名单" },
    { "blacklist.gui.add.label", "§b请选择添加至黑名单玩家:" },
    { "blacklist.gui.add.input1", "§e请输入加入黑名单原因" },
    { "blacklist.gui.add.input2", "§e请输入加入黑名单时间" },
    { "blacklist.gui.add.input1.placeholder", "具体原因 (任意)" },
    { "blacklist.gui.add.input2.placeholder", "具体时间 (数字/0为永久加入)[/hour]" },
    { "blacklist.gui.remove.title", "§eLOIBlacklist §b-> §a删除黑名单" },
    { "blacklist.gui.remove.label", "§b请选择删除黑名单对象:" },
    { "blacklist.gui.info.label", "§a对象ID: §r${id}\n§d对象名称: §r${player}\n§b提交原因: §r${cause}\n§6提交时间: §r${subtime}\n§e解除时间: §r${time}" },
    { "blacklist.gui.info.remove", "§c删除该黑名单" },
    { "mute.log1", "玩家 {player}({player.uuid}) 被禁言, 原因: ${cause}" },
    { "mute.log2", "目标 ${target} 已解除禁言" },
    { "mute.tips", "§4您已被禁言, 无法发送消息 §e解除时间: §r${time} §b原因: §r${cause}" },
    { "mute.gui.title", "§eLOIMute §b-> §c服务器禁言" },
    { "mute.gui.label", "§a功能如下:" },
    { "mute.gui.addMute", "§c添加禁言\n§4将玩家添加至禁言" },
    { "mute.gui.removeMute", "§a删除禁言\n§4将玩家从禁言中移除" },
    { "mute.gui.add.title", "§eLOIMute §b-> §c添加禁言" },
    { "mute.gui.add.label", "§b请选择添加至禁言玩家:" },
    { "mute.gui.add.input1", "§e请输入禁言原因" },
    { "mute.gui.add.input2", "§e请输入禁言时间" },
    { "mute.gui.add.input1.placeholder", "具体原因 (任意)" },
    { "mute.gui.add.input2.placeholder", "具体时间 (数字/0为永久禁言)[/hour]" },
    { "mute.gui.remove.title", "§eLOIMute §b-> §a删除禁言" },
    { "mute.gui.remove.label", "§b请选择删除禁言对象:" },
    { "mute.gui.info.label", "§a提交对象: §r${target}\n§d对象名称: §r${player}\n§b提交原因: §r${cause}\n§6提交时间: §r${subtime}\n§e解除时间: §r${time}" },
    { "mute.gui.info.remove", "§c删除该禁言" },
    { "cdk.log1", "新的CDK: ${cdk} 已创建" },
    { "cdk.log2", "CDK: ${cdk} 已被删除" },
    { "cdk.log3", "玩家 {player}({player.uuid}) 总换CDK: ${cdk}" },
    { "cdk.convert.tips1", "当前 CDK 不存在, 无法总换内容" },
    { "cdk.convert.tips2", "总换失败, 该 CDK 已经使用过了" },
    { "cdk.convert.tips3", "CDK 总换成功, 具体内容已下发" },
    { "cdk.gui.title", "§eLOICdk §b-> §a总换码" },
    { "cdk.gui.label", "§b功能如下:" },
    { "cdk.gui.convert.input", "§e请输入CDK" },
    { "cdk.gui.convert.input.placeholder", "具体CDK的ID (任意)" },
    { "cdk.gui.addCdk", "§a创建CDK\n§4添加一个空白CDK" },
    { "cdk.gui.removeCdk", "§4删除CDK\n§4删除一个CDK" },
    { "cdk.gui.addAward", "§a添加奖励\n§4将奖励添加至CDK中" },
    { "cdk.gui.new.input1", "§e请输入CDK" },
    { "cdk.gui.new.input2", "§eCDK存在时间" },
    { "cdk.gui.new.input1.placeholder", "CDK的ID (任意)" },
    { "cdk.gui.new.input2.placeholder", "具体时间 (数字/0为永久存在)[/hour]" },
    { "cdk.gui.new.switch", "§e是否只能总换一次" },
    { "cdk.gui.remove.label", "§b请选择要删除的CDK" },
    { "cdk.gui.remove.content", "§e§l确定删除 CDK 为 §r${cdk} §e§l吗" },
    { "cdk.gui.remove.yes", "§c确认删除" },
    { "cdk.gui.remove.no", "§a取消删除" },
    { "cdk.gui.award.label", "§b请选择要添加内容的CDK:" },
    { "cdk.gui.award.info.label", "§a目前选择 §rCDK §a为 §a${cdk}\n§d单次总换: §r${personal}\n§b过期时间: §r${time}" },
    { "cdk.gui.award.score", "§a添加计分板奖励" },
    { "cdk.gui.award.item", "§e添加物品奖励" },
    { "cdk.gui.award.title", "§b添加称号奖励" },
    { "cdk.gui.award.score.input1", "§e请输入计分板名称" },
    { "cdk.gui.award.score.input2", "§e请输入奖励数量" },
    { "cdk.gui.award.score.input1.placeholder", "具体的 objective 计分板 (限定)" },
    { "cdk.gui.award.score.input2.placeholder", "给予的 Score 数量 (数字)" },
    { "cdk.gui.award.item.dropdown", "§a请选择物品解析类型" },
    { "cdk.gui.award.item.input1", "§e请输入物品" },
    { "cdk.gui.award.item.input2", "§e请输入物品名称" },
    { "cdk.gui.award.item.input3", "§e请输入物品数量" },
    { "cdk.gui.award.item.input4", "§e请输入物品特殊值" },
    { "cdk.gui.award.item.input1.placeholder", "物品的ID或NBT (限定)" },
    { "cdk.gui.award.item.input2.placeholder", "物品的名称 (任意)" },
    { "cdk.gui.award.item.input3.placeholder", "物品的数量 (数字)" },
    { "cdk.gui.award.item.input4.placeholder", "物品的特殊值 (数字)" },
    { "cdk.gui.award.title.input1", "§e请输入要添加的称号" },
    { "cdk.gui.award.title.input2", "§e请输入称号存在的时间" },
    { "cdk.gui.award.title.input1.placeholder", "称号内容 (任意)" },
    { "cdk.gui.award.title.input2.placeholder", "具体时间 (数字/0为永久存在)[/hour]" },
    { "menu.log1", "玩家 {player}({player.uuid}) 新建菜单 ${menu}" },
    { "menu.log2", "玩家 {player}({player.uuid}) 删除菜单 ${menu}" },
    { "menu.log3", "玩家 {player}({player.uuid}) 删除菜单 ${menu} 的组件 ${customize}" },
    { "menu.log4", "玩家 {player}({player.uuid}) 添加命令至菜单 ${menu}" },
    { "menu.log5", "玩家 {player}({player.uuid}) 设置菜单 ${menu} 的默认内容" },
    { "menu.log6", "玩家 {player}({player.uuid}) 向菜单 ${menu} 添加组件" },
    { "menu.gui.title", "§e§lLOICollection -> §b服务器菜单" },
    { "menu.gui.label", "§b功能如下:" },
    { "menu.gui.button1", "§a新建表单\n§4新建一个自定义表单" },
    { "menu.gui.button2", "§b删除表单\n§4删除一个自定义表单" },
    { "menu.gui.button3", "§d添加内容\n§4给自定义表单添加内容" },
    { "menu.gui.button1.input1", "§e请输入表单ID" },
    { "menu.gui.button1.input2", "§e请输入退出表单时返回内容" },
    { "menu.gui.button1.input3", "§e请输入没有指定权限时返回内容" },
    { "menu.gui.button1.input4", "§e请输入没有足够Score时返回内容" },
    { "menu.gui.button1.input5", "§e请输入表单内容" },
    { "menu.gui.button1.input6", "§e请输入表单标题" },
    { "menu.gui.button1.dropdown", "§b请选择表单类型" },
    { "menu.gui.button1.slider", "§b请选择表单权限等级" },
    { "menu.gui.button2.content", "§e§l确定删除表单 §r${menu} §e§l吗" },
    { "menu.gui.button2.yes", "§c确认删除" },
    { "menu.gui.button2.no", "§a取消删除" },
    { "menu.gui.button3.label", "§e§l设置表单 §r${menu}" },
    { "menu.gui.button3.setting", "§d设置内容\n§4设置表单内容" },
    { "menu.gui.button3.new", "§9添加组件\n§4添加自定义组件至表单" },
    { "menu.gui.button3.remove", "§b删除组件\n§4从表单中删除指定组件" },
    { "menu.gui.button3.command", "§a设置命令\n§4设置表单提交时执行命令" },
    { "menu.gui.button3.new.input1", "§e请输入组件ID" },
    { "menu.gui.button3.new.input2", "§e请输入组件标题" },
    { "menu.gui.button3.new.input3", "§e请输入组件图标" },
    { "menu.gui.button3.new.input4", "§e请输入使用该组件时所需要的Score目标" },
    { "menu.gui.button3.new.input5", "§e请输入使用该组件时所需要的Score分数" },
    { "menu.gui.button3.new.input6", "§e请输入使用该组件时所执行的内容" },
    { "menu.gui.button3.new.dropdown1", "§e请选择组件类型" },
    { "menu.gui.button3.new.dropdown2", "§e请选择按钮类型" },
    { "menu.gui.button3.new.slider", "§b请选择组件权限等级" },
    { "menu.gui.button3.remove.content", "§e§l确定删除组件 §r${customize} §e§l吗" },
    { "menu.gui.button3.remove.yes", "§c确认删除" },
    { "menu.gui.button3.remove.no", "§a取消删除" },
    { "menu.gui.button3.command.line", "§a第${index}行" },
    { "menu.gui.button3.command.addLine", "§b添加一行" },
    { "menu.gui.button3.command.removeLine", "§c删除一行" }, 
    { "tpa.log1", "已将玩家 ${player1} 传送到玩家 ${player2}" },
    { "tpa.log2", "玩家 {player}({player.uuid}) 添加了 Tpa 黑名单 ${target}" },
    { "tpa.log3", "玩家 {player}({player.uuid}) 移除了 Tpa 黑名单 ${target}" },
    { "tpa.tips1", "§c当前所需 Score 不足, 目前所需 §r${score}" },
    { "tpa.tips2", "§c您上传的黑名单数量已达上限 §r${size}" },
    { "tpa.here", "§e玩家 §b{player} §e邀请你传送到他的位置" },
    { "tpa.there", "§e玩家 §b{player} §e请求传送到你的位置" },
    { "tpa.yes", "§a同意传送" },
    { "tpa.no", "§c拒绝传送" },
    { "tpa.no.tips", "§c玩家 §r${player} §c拒绝了你的请求" },
    { "tpa.gui.title", "§eLOITpa §b-> §a玩家互传" },
    { "tpa.gui.label", "§b功能如下:" },
    { "tpa.gui.label2", "§e请选择玩家:" },
    { "tpa.gui.dropdown", "§b请选择类型:" },
    { "tpa.gui.setting.title", "§eLOITpa §b-> §a个人设置" },
    { "tpa.gui.setting.label", "§b功能如下:" },
    { "tpa.gui.setting.generic", "§a通用设置\n§4个人 Tpa 通用设置" },
    { "tpa.gui.setting.blacklist", "§b黑名单设置\n§4个人 Tpa 黑名单设置" },
    { "tpa.gui.setting.generic.switch1", "§b拒绝所有人的tpa请求 [§c关闭§b | §a开启§b]" },
    { "tpa.gui.setting.blacklist.add", "§a添加黑名单\n§4添加玩家至黑名单" },
    { "tpa.gui.setting.blacklist.add.label", "§a请选择要添加的玩家" },
    { "tpa.gui.setting.blacklist.set.label", "§a提交对象: §r${target}\n§d对象名称: §r${player}\n§6提交时间: §r${time}" },
    { "tpa.gui.setting.blacklist.set.remove", "§c删除目标" },
    { "shop.log1", "玩家 {player}({player.uuid}) 新建商店表单 ${menu}" },
    { "shop.log2", "玩家 {player}({player.uuid}) 删除商店菜单 ${menu}" },
    { "shop.log3", "玩家 {player}({player.uuid}) 删除商店菜单 ${menu} 的组件 ${customize}" },
    { "shop.log4", "玩家 {player}({player.uuid}) 设置商店菜单 ${menu} 的默认内容" },
    { "shop.log5", "玩家 {player}({player.uuid}) 向商店菜单 ${menu} 添加物品组件" },
    { "shop.gui.title", "§e§lLOICollection -> §b服务器商店" },
    { "shop.gui.label", "§b功能如下:" },
    { "shop.gui.button1", "§a新建表单\n§4新建一个商店表单" },
    { "shop.gui.button2", "§b删除表单\n§4删除一个商店表单" },
    { "shop.gui.button3", "§d添加内容\n§4给商店表单添加内容" },
    { "shop.gui.button1.input1", "§e请输入表单ID" },
    { "shop.gui.button1.input2", "§e请输入退出表单时返回内容" },
    { "shop.gui.button1.input3", "§e请输入没有指定称号时返回内容" },
    { "shop.gui.button1.input4", "§e请输入没有足够物品时返回内容" },
    { "shop.gui.button1.input5", "§e请输入没有足够Score时返回内容" },
    { "shop.gui.button1.input6", "§e请输入表单内容" },
    { "shop.gui.button1.input7", "§e请输入表单标题" },
    { "shop.gui.button1.dropdown", "§b请选择表单类型" },
    { "shop.gui.button2.content", "§e§l确定删除商店表单 §r${menu} §e§l吗" },
    { "shop.gui.button2.yes", "§c确认删除" },
    { "shop.gui.button2.no", "§a取消删除" },
    { "shop.gui.button3.label", "§e§l设置表单 §r${menu}" },
    { "shop.gui.button3.setting", "§d设置内容\n§4设置商店表单内容" },
    { "shop.gui.button3.new", "§9添加组件\n§4添加物品组件至表单" },
    { "shop.gui.button3.remove", "§b删除组件\n§4从表单中删除指定组件" },
    { "shop.gui.button3.new.input1", "§e请输入组件标题" },
    { "shop.gui.button3.new.input2", "§e请输入组件图标" },
    { "shop.gui.button3.new.input3", "§e请输入组件介绍" },
    { "shop.gui.button3.new.input4", "§e请输入使用该组件时所需要的Score目标" },
    { "shop.gui.button3.new.input5", "§e请输入使用该组件时所需要的Score分数" },
    { "shop.gui.button3.new.input6", "§e请输入使用该组件时所执行的内容" },
    { "shop.gui.button3.new.input7", "§e请输入组件执行组件文本 - 1" },
    { "shop.gui.button3.new.input8", "§e请输入组件执行组件文本 - 2" },
    { "shop.gui.button3.new.input9", "§e请输入物品组件持续时间" },
    { "shop.gui.button3.new.dropdown", "§e请选择组件类型" },
    { "shop.gui.button3.remove.content", "§e§l确定删除物品组件 §r${customize} §e§l吗" },
    { "shop.gui.button3.remove.yes", "§c确认删除" },
    { "shop.gui.button3.remove.no", "§a取消删除" },
    { "pvp.log1", "玩家 {player}({player.uuid}) 开启了PVP" },
    { "pvp.log2", "玩家 {player}({player.uuid}) 关闭了PVP" },
    { "pvp.off", "§4双方均未开启PVP, 目前无法造成伤害" },
    { "pvp.gui.title", "§eLOIPvp §b-> §a服务器PVP" },
    { "pvp.gui.label", "§b功能如下:" },
    { "pvp.gui.on", "§4开启PVP" },
    { "pvp.gui.off", "§a关闭PVP" },
    { "wallet.log", "玩家 ${player1} 向玩家 ${player2} 转账 ${money}" },
    { "wallet.showOff", "{player} 炫出了自己的钱包: ${money}" },
    { "wallet.tips", "§4您的Score不足, 无法转账" },
    { "wallet.gui.title", "§eLOIWallet §b-> §a个人钱包" },
    { "wallet.gui.label", "§b拥有金钱: ${money}\n§e今日税率: ${tax}" },
    { "wallet.gui.transfer", "§a玩家转账" },
    { "wallet.gui.wealth", "§b查看Score" },
    { "wallet.gui.offlineTransfer", "§c离线转账" },
    { "wallet.gui.transfer.label1", "§b请选择玩家" },
    { "wallet.gui.transfer.label2", "§a目前选择玩家: §r${target}" },
    { "wallet.gui.transfer.input", "§e请输入金额" },
    { "wallet.gui.transfer.input.placeholder", "具体Score (数字)" },
    { "chat.log1", "玩家 {player}({player.uuid}) 更改称号为 {player.title}" },
    { "chat.log2", "玩家 {player}({player.uuid}) 获得称号 ${title}" },
    { "chat.log3", "玩家 {player}({player.uuid}) 移除称号 ${title}" },
    { "chat.log4", "玩家 {player}({player.uuid}) 称号 ${title} 已达到预定时间" },
    { "chat.log5", "玩家 {player}({player.uuid}) 添加了 Chat 黑名单 ${target}" },
    { "chat.log6", "玩家 {player}({player.uuid}) 移除了 Chat 黑名单 ${target}" },
    { "chat.gui.title", "§eLOIChat §b-> §a个人称号" },
    { "chat.gui.label", "§b功能如下:" },
    { "chat.gui.setTitle", "§a设置称号\n§4设置自己的称号显示" },
    { "chat.gui.setBlacklist", "§e设置黑名单\n§4设置目标消息内容黑名单" },
    { "chat.gui.setTitle.label", "§a当前配戴称号: §f{player.title}\n§e称号到期时间: §f{player.title.time}" },
    { "chat.gui.setTitle.dropdown", "§b请选择配戴称号" },
    { "chat.gui.setBlacklist.tips1", "§c您上传的黑名单数量已达上限 §r${size}" },
    { "chat.gui.setBlacklist.add", "§a添加黑名单" },
    { "chat.gui.setBlacklist.add.label", "§a请选择要添加的玩家" },
    { "chat.gui.setBlacklist.set.label", "§a提交对象: §r${target}\n§d对象名称: §r${player}\n§6提交时间: §r${time}" },
    { "chat.gui.setBlacklist.set.remove", "§c删除目标" },
    { "chat.gui.manager.add", "§a添加称号\n§4添加称号给指定玩家" },
    { "chat.gui.manager.remove", "§c删除称号\n§4从玩家上删除指定称号" },
    { "chat.gui.manager.add.label", "§a请选择要添加的玩家" },
    { "chat.gui.manager.add.input1", "§e请输入要添加的称号" },
    { "chat.gui.manager.add.input2", "§e请输入称号存在的时间[/hour](0为永久存在)" },
    { "chat.gui.manager.remove.label", "§a请选择要删除的玩家" },
    { "chat.gui.manager.remove.dropdown", "§e请选择要删除的称号" },
    { "notice.log1", "玩家 {player}({player.uuid}) 重新编辑了公告" },
    { "notice.log2", "玩家 {player}({player.uuid}) 添加了公告 ${notice}" },
    { "notice.log3", "玩家 {player}({player.uuid}) 删除了公告 ${notice}" },
    { "notice.gui.title", "§eLOINotice §b-> §a公告系统" },
    { "notice.gui.label", "§b功能如下:" },
    { "notice.gui.add", "§a添加公告\n§4添加一条公告" },
    { "notice.gui.remove", "§c删除公告\n§4删除一条公告" },
    { "notice.gui.add.input1", "§e请输入公告ID" },
    { "notice.gui.add.input2", "§e请输入公告标题" },
    { "notice.gui.add.input3", "§e请输入公告优先级" },
    { "notice.gui.add.input1.placeholder", "公告ID (任意)" },
    { "notice.gui.add.input2.placeholder", "公告标题 (任意)" },
    { "notice.gui.add.input3.placeholder", "公告优先级 (数字)" },
    { "notice.gui.add.switch", "§b是否开启公告提示 [§c关闭§b | §a开启§b]" },
    { "notice.gui.remove.content", "§e§l确定删除公告 §r${notice} §e§l吗" },
    { "notice.gui.remove.yes", "§c确认删除" },
    { "notice.gui.remove.no", "§a取消删除" },
    { "notice.gui.edit.title", "§e设置标题" },
    { "notice.gui.edit.line", "§a第${index}行" },
    { "notice.gui.edit.show", "§b是否开启公告提示 [§c关闭§b | §a开启§b]" },
    { "notice.gui.edit.operation", "§e执行目标" },
    { "notice.gui.edit.operation.no", "§a不进行操作" },
    { "notice.gui.edit.operation.add", "§b添加一行" },
    { "notice.gui.edit.operation.remove", "§c删除一行" },
    { "notice.gui.setting.switch1", "§b关闭公告 [§c关闭§b | §a开启§b]" },
    { "market.log1", "玩家 {player}({player.uuid}) 购买物品 ${item}" },
    { "market.log2", "玩家 {player}({player.uuid}) 出售物品 ${item}" },
    { "market.log3", "玩家 {player}({player.uuid}) 下架物品 ${item}" },
    { "market.log4", "玩家 {player}({player.uuid}) 添加了 Market 黑名单 ${target}" },
    { "market.log5", "玩家 {player}({player.uuid}) 移除了 Market 黑名单 ${target}" },
    { "market.gui.title", "§e§lLOIMarket -> §b玩家市场" },
    { "market.gui.label", "§b功能如下:" },
    { "market.gui.sell.introduce", "§b物品介绍: §r${introduce}\n§e物品价格: §r${score}\n§a物品Nbt: §r${nbt}\n§d上传玩家: §r${player}" },
    { "market.gui.sell.sellItem", "§a售出物品\n§4售出自己的物品" },
    { "market.gui.sell.sellItemContent", "§b查看售出物品\n§4查看自己售出的物品" },
    { "market.gui.sell.blacklist", "§e黑名单管理\n§4管理自己上传的玩家黑名单" },
    { "market.gui.sell.sellItem.dropdown", "§b请选择物品" },
    { "market.gui.sell.sellItem.dropdown.text", "${item} §bx${count}" },
    { "market.gui.sell.sellItem.input1", "§e请输入物品名称" },
    { "market.gui.sell.sellItem.input2", "§e请输入物品图标路径" },
    { "market.gui.sell.sellItem.input3", "§e请输入物品介绍" },
    { "market.gui.sell.sellItem.input4", "§e请输入物品售卖Score价格" },
    { "market.gui.sell.sellItem.input1.placeholder", "物品名称 (任意)" },
    { "market.gui.sell.sellItem.input2.placeholder", "物品图标路径 (任意)" },
    { "market.gui.sell.sellItem.input3.placeholder", "物品介绍 (任意)" },
    { "market.gui.sell.sellItem.input4.placeholder", "物品售卖Score价格 (数字)" },
    { "market.gui.sell.sellItem.tips1", "§a您的物品 §f${item} §a已售出" },
    { "market.gui.sell.sellItem.tips2", "§a物品 §f${item} §a已下架" },
    { "market.gui.sell.sellItem.tips3", "§c您没有足够的分数购买这个物品" },
    { "market.gui.sell.sellItem.tips4", "§c您上传的物品已达上限 §r${size}" },
    { "market.gui.sell.sellItem.tips5", "§c您上传的黑名单数量已达上限 §r${size}" },
    { "market.gui.sell.sellItemContent.button1", "§c下架物品\n§4下架该物品" },
    { "market.gui.sell.blacklist.add", "§a添加黑名单\n§4添加玩家至黑名单" },
    { "market.gui.sell.blacklist.add.label", "§a请选择要添加的玩家" },
    { "market.gui.sell.blacklist.set.label", "§a提交对象: §r${target}\n§d对象名称: §r${player}\n§6提交时间: §r${time}" },
    { "market.gui.sell.blacklist.set.remove", "§c删除目标" },
    { "market.gui.sell.buy.button1", "§e购买物品\n§4购买当前物品" },
    { "behaviorevent.event.playerconnect", "玩家 {0} 在维度ID为 {1} 的 ({2}, {3}, {4}) 位置加入服务器" },
    { "behaviorevent.event.playerdisconnect", "玩家 {0} 在维度ID为 {1} 的 ({2}, {3}, {4}) 位置离开服务器" },
    { "behaviorevent.event.playerchat", "玩家 {0} 说: {1}" },
    { "behaviorevent.event.playeraddexperience", "玩家 {0} 获得经验 {1}" },
    { "behaviorevent.event.playerattack", "玩家 {0} 因为 {1} 攻击实体 {2}" },
    { "behaviorevent.event.playerchangeperm", "玩家 {0} 更改权限组为 {1}" },
    { "behaviorevent.event.playerdestroyblock", "玩家 {0} 在维度ID为 {1} 的 ({2}, {3}, {4}) 位置破坏 Nbt 为 {5} 的方块" },
    { "behaviorevent.event.playerplaceblock", "玩家 {0} 在维度ID为 {1} 的 ({2}, {3}, {4}) 位置放置 Nbt 为 {5} 的方块" },
    { "behaviorevent.event.playerdie", "玩家 {0} 因 {1} 死亡" },
    { "behaviorevent.event.playerpickupitem", "玩家 {0} 捡起 Nbt 为 {1} 的物品" },
    { "behaviorevent.event.playerinteractblock", "玩家 {0} 与维度ID为 {1} 的 ({2}, {3}, {4}) 位置的 Nbt 为 {5} 的方块交互" },
    { "behaviorevent.event.playerrespawn", "玩家 {0} 在维度ID为 {1} 的 ({2}, {3}, {4}) 位置进行重生" },
    { "behaviorevent.event.playeruseitem", "玩家 {0} 使用 Nbt 为 {1} 的物品" }
};
