on:
    pull_request:
        paths:
            - ".github/workflows/build.yml"
            - "src/**"
            - "xmake.lua"
    push:
        paths:
            - ".github/workflows/build.yml"
            - "src/**"
            - "xmake.lua"
        branches:
            - "**" 
        tags-ignore:
            - "**"
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                shared:
                    - true
                    - false
                mode:
                    - debug
                    - release

        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v5
            - uses: xmake-io/github-action-setup-xmake@v1
            - uses: actions/cache@v4
              with:
                path: |
                    ~/AppData/Local/.xmake
                key: xmake-${{ hashFiles('xmake.lua') }}
                restore-keys: |
                    xmake-
            
            - run: |
                xmake repo -u
            
            - run: |
                xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y --shared=${{ matrix.shared }}
            
            - run: |
                xmake -v -y
            
            - uses: actions/upload-artifact@v5
              with:
                name: ${{ github.event.repository.name }}-${{ matrix.shared == false && 'ES-' || '' }}${{ matrix.mode }}-windows-x64-${{ github.sha }}
                path: |
                    build/bin/
            